openapi: 3.0.0
info:
  title: Inventory Management API
  version: 1.0.0
  description: REST API for user authentication and product inventory management
servers:
  - url: http://localhost:8080
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered

  /api/auth/login:
    post:
      summary: Login an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login success (JWT returned)

  /api/products:
    post:
      summary: Add a new product
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, type, sku, quantity, price]
              properties:
                name:
                  type: string
                type:
                  type: string
                sku:
                  type: string
                image_url:
                  type: string
                description:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
      responses:
        '201':
          description: Product created

    get:
      summary: Get all products with pagination
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: List of products

  /api/products/{id}/quantity:
    put:
      summary: Update quantity of a product
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [quantity]
              properties:
                quantity:
                  type: integer
      responses:
        '200':
          description: Quantity updated

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
